services:

  db:
    image: postgres:18
    container_name: employees_db
    environment:
      POSTGRES_DB: employees_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d employees_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Backend.Dockerfile
    container_name: employees_backend
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Database=employees_db;Username=postgres;Password=postgres"
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Frontend.Dockerfile
    container_name: employees_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata: