// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408181430_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hired_at");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("salary");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f3c2c4b-0c8e-4c1a-9b8d-2e4a9f1f7c11"),
                            Department = "Продажи",
                            FullName = "Иван Иванов",
                            HiredAt = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Менеджер",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = new Guid("a1b4d8e2-5f6c-4d9a-8f22-9c3e7b6a1d44"),
                            Department = "Маркетинг",
                            FullName = "Мария Петрова",
                            HiredAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Аналитик",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = new Guid("c7e2f9a1-3b4d-4f8e-92aa-1f6b3c9d7e55"),
                            Department = "IT",
                            FullName = "Сергей Кузнецов",
                            HiredAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Разработчик",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = new Guid("9d1f4b22-8c3a-4e77-b1d9-5f2a6c4e8f66"),
                            Department = "Финансы",
                            FullName = "Ольга Смирнова",
                            HiredAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Бухгалтер",
                            Salary = 55000m
                        },
                        new
                        {
                            Id = new Guid("e4b7a9c3-2d1f-4f6a-8b33-7c9e1a2d3f77"),
                            Department = "Кадры",
                            FullName = "Алексей Морозов",
                            HiredAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "HR",
                            Salary = 52000m
                        },
                        new
                        {
                            Id = new Guid("f8c1d2e3-4b5a-4c6d-9e88-1a3f7b2c4d88"),
                            Department = "Маркетинг",
                            FullName = "Екатерина Волкова",
                            HiredAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Дизайнер",
                            Salary = 58000m
                        },
                        new
                        {
                            Id = new Guid("12a4c6e8-9b3d-4f1e-8c77-5d2e9a1b3c99"),
                            Department = "IT",
                            FullName = "Дмитрий Соколов",
                            HiredAt = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Менеджер проектов",
                            Salary = 80000m
                        },
                        new
                        {
                            Id = new Guid("7b9e2d1c-3f4a-4c8e-91aa-6e5c3d2b1a10"),
                            Department = "Администрация",
                            FullName = "Анастасия Фёдорова",
                            HiredAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Секретарь",
                            Salary = 40000m
                        },
                        new
                        {
                            Id = new Guid("d4c3b2a1-8e7f-4a6c-9d55-2b1c4e3f5a21"),
                            Department = "IT",
                            FullName = "Николай Орлов",
                            HiredAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Тестировщик",
                            Salary = 60000m
                        },
                        new
                        {
                            Id = new Guid("8e1f2c3d-4b5a-4d6e-8f99-7c2a1b3e4d32"),
                            Department = "Маркетинг",
                            FullName = "Татьяна Крылова",
                            HiredAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = "Маркетолог",
                            Salary = 57000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
